### ISSUE TITLE
Random case clause error

### ISSUE THREAD

**Issue by ConnorRigby** [Sqlite-Ecto/sqlite_ecto2#204]
I'm getting this error seemingly randomly, but pretty frequently:
```
** (CaseClauseError) no case clause matching: {:raise, 
%Sqlite.DbConnection.Error{connection_id: nil, message: "Disconnected", sqlite: nil}}
```

I've noticed this is happening in [travis](https://travis-ci.org/scouten/sqlite_ecto2/jobs/304195408#L728) too

**Comment by michaelkschmidt** [comment]
We fight this a lot too.  I believe it is caused by a GenServer timeout anytime SQLite takes longer than 5s to complete an operation
