### ISSUE TITLE
Managing several databases via a single repo?

### ISSUE THREAD

**Issue by kluufger** [Sqlite-Ecto/sqlite_ecto2#220]
👋@ConnorRigby

Firstly, thank you for taking care of this project!

Secondly, I have a question ... I'm playing around with a riak core + sqlite(s) setup, and thought it would be nice to have a "pool" of sqlites on each node to allow for at least some concurrency. So is it possible to have multiple databases open for a single repo? If not, should I start a repo for each opened database? Or maybe I should just use `sqlitex` directly?

**Comment by ConnorRigby** [comment]
Can you give an example of a problem you are trying to solve?

For what it is worth this adapter uses pool boy which by default starts a pool of 10 processes that handle incoming calls. The Sqlite website/docs has a pretty opinionated page on concurrent programming and how they don't really think it's a great idea for Sqlite. Basically you can have many different connections open to Sqlite reading data no problem, but there can only ever be exactly _one_ write at a time.

**Comment by kluufger** [comment]
> but there can only ever be exactly one write at a time.

That's what I want to avoid by having multiple databases (files) open.

**Comment by ConnorRigby** [comment]
So the same file open multiple times, or the same Repo opening many replicas of the same data?

**Comment by kluufger** [comment]
Neither, I guess. The repo would open multiple separate databases.

**Comment by kluufger** [comment]
I guess I want something similar to http://www.actordb.com/, but much simpler and without raft.

**Comment by kluufger** [comment]
I'll try using separate repos (for each user's database) under a dynamic supervisor for now.

**Comment by kluufger** [comment]
> I'll try using separate repos (for each user's database) under a dynamic supervisor for now.

https://github.com/servers-and-stuff/dynamic_repo_sqlite

**Comment by kluufger** [comment]
@venkatd I have a [branch](https://github.com/servers-and-stuff/sqlite_ecto2) which supported ecto 3.0-rc and an (incomplete) [demo](https://github.com/servers-and-stuff/dynamic_repo_sqlite) of what I was asking for here.
